.common_files/stow/script/setup
.gitmessage

As our projects get old, the value of great quality commit messages increases. In many cases we wish previous co-workers and previous versions of ourselves had spent more time explaining why they were doing what they were doing, instead of just explaining what the code does.Even things that are blindingly obvious now can be very unclear in a few years.
It specifically prompts the user to answer 'why?' and 'how?'
As a bonus, this message is formatted in a way that makes github pull requests look good. That should save time and improve the quality of our PR communication. …

Apply this template automatically for everyone using the common files

---

.bashrc

Many moons ago, Rails changed the correct way to start a console or server. These shortcuts were never updated and no longer work.
Changes the command so it actually does what's intended.

Update rails console and server shortcuts

---

.common_files/cf.Darwin.conf

The default open file limit is too low for some of our tools to run properly, notably automation.  Also, it's 2019, `2**8` is absurdly low.  Even this is probably absurdly low.
Raise the open file limit from `2**8` to `2**11`.
Reported in flowdock here: https://www.flowdock.com/app/expected-behavior/team-ops/threads/i5xint49xRwg-I87_iSFToofOJu
Reported in meat-space with many cursewords by various developers.
Co-authored-by: Joel Meador <joel@expectedbehavior.com>

Raise open file limit

---

.gitmessage

Alex wasn't on the Co-authored-by list. Adding him to the list makes it
easier for others to include him in their commit messages.
It adds Alex to the list.

Updates the commit template to include Alex

---

.common_files/cf.Darwin.conf

Some of the test files in Instrumental require more open files than that to run succesfully and the error you get if you don't have it is extremely obtuse (no error message, just stops running).
Print a warning when you open a terminal and gives directions on how to fix the problem.
Co-authored-by: Alex Overbeck <alex@expectedbehavior.com>

Print a warning message if open file limits are less than 200k

---

.emacs.d/config.org

It's a community config, so there should be some guidelines about
- what users can expect when using the config
- what contributions are likely to be accepted
I titled it "About" because it seemed like an easy place to
start. It's intended to be a starting place, but it's probably not the
end.
https://3.basecamp.com/3093825/buckets/14355728/todos/2209223512

Add an "About" section to config.org

---

.emacs.d/config.org

One of the primary goals of the config is to have every configuration
change documented so future-you and anybody else that reads it
understands why that config exists instead of just what it does.
I expanded the description of a few things and split the generic
"clean ui" group into separate entries that were easier to document.

Add documentation to the config

---

.emacs.d/config.org
script/setup

There's a description of Org Roam in the files. I'm using it as part of my organization system. It is awesome.

Emacs org roam m1 with setup

---

.emacs.d/config.org
script/setup

Add Silver Searcher as an option for projectile searching
This is branched off of #19, because I can't live without OrgRoam. It makes the diff pretty useless right now, but you can tell what's happening if you just look at the most recent commit.

silver searcher in emacs

---

.common_files/lib/git.bash
.emacs.d/config.org
script/setup

Details in the commit message.
This is branched from #20, which is branched from #19. Ideally, I wouldn't branch from things that haven't been merged yet, but I'm already using these things and it's inconvenient to flop around.

Add an alias to push and set git branch and tracking

---

.emacs.d/config.org

It's no longer listed in MELPA
Del Taco

Remove the Emacs theme "melancholy"

---

.emacs.d/config.org

This is an evolution in keeping a place for random scratch
information. I started with a simple append only text file. That
became hard to search when it became many thousands of
undifferentiated lines, so I tried using an org file. That led me to
having a heading for each day. That gets unwieldy when I'm working on
many different ideas on the same idea. I prefer to have as few
foldable layers as possible. Having a file per day was the obvious choice.
Since org roam already provides this feature, it's incredibly
easy. The dailies feature is in a separate package, so I included
it. That package includes a keymap that follows the other org roam
patterns. It's got a bunch of …

Enable org roam dailies and the basic keymap

---

.emacs.d/config.org

As previously configured, text beneath a node in org would automatically be indented to the level of the node, so it might look like
```
*
foo
**
foo
***
foo
```
I think that's maddening
The org-adapt-indentation controls that feature. I turned it off. It will now look like
```
*
foo
**
foo
***
foo
```

Stop automatically indenting org text to the level of the node

---

.gitmessage

The list of people who could possibly contribute to a commit has changed, let's freshen up this template to reflect the current list.

Update the git commit template

---

.gitmessage

This makes it exactly match our PR template, and hopefully reduces the likelihood of overly generic commit message first lines (which are what you see in summaries in glg and github).
See discussion in https://github.com/expectedbehavior/doc_raptor/commit/f6c1fa6cf314133487259c49b7ca352dde88adca#commitcomment-114870078

Merge in gitmessage changes from PR template 

---

.ssh/config

We want some ssh config for EB, but people might have personal stuff as
well.
Move to a config.d directory and include all files in that directory.
People can use stow to add personal configuration.

Make it easier to manage ssh config files

---

.common_files/stow/script/setup
.common_files/stow/secrets
documentation/storing_secrets.md
script/setup_secrets

We'd like it to be easy to store sensitive data.
Add a script to help setup the secrets volume. Also update the stow
script to automatically use the secrets volume if it's setup.

Take a stab at making it easier to setup secrets

---

.bash_profile

I believe I was getting an error message during computer setup because
the java plugin wasn't installed yet. This resulted in some weird text
in the PATH (an error message from asdf).
Check if the asdf java plugin is installed before setting the JAVA_HOME.

Prevent asdf error before java is installed

---

.bash_profile

This is required in order to get forking to work properly in the docraptor tests. as things labeled 'unsafe' go, it is fairly safe. We have seen this before and this was the solution then, too. Read more: https://stackoverflow.com/questions/52671926/rails-may-have-been-in-progress-in-another-thread-when-fork-was-called

export a flag to disable objc fork safety. 

---

.common_files/cf.jason.conf
.common_files/stow/common-files-jason/.common_files/bin/code_wait

VSCode is faster and seems to be getting more development than Atom.
I've been using it for awhile and have been enjoying it so I'll make it
offical.
Switch the EDITOR variable to a newly added script to handle opening the
editor and waiting for the file to be closed.
This also adds a comment to help me waste less time next time trying a
simpler strategy. This avoids issues like:
```
$ EDITOR="code --wait" crontab -e
crontab: code --wait: No such file or directory
crontab: "code --wait" exited with status 1
```

Switch Jason's EDITOR to vscode

---

Brewfile

`File.dirname(__FILE__)` was returning `~/.dotfiles` instead of the
user's home directory. This cause us to not find user brewfiles that
were linked through stow.
Look for `.brewfiles` in the user's home directory.
--------------------------------------
- Run test suite?
- Add new tests?
- Consider security implications and practices?

Fix brewfile issue

---

script/install/homebrew

On the first run we install homebrew, but we don't load it into the
shell. This causes the script to fail when it tries to use `brew`.
Setup homebrew after installing it.
--------------------------------------
- Run test suite?
- Add new tests?
- Consider security implications and practices?

Fix script/setup on initial run

---

script/install/dropbox

We can make it clearer what should happen next, and speed things up for
the user a bit if we open Dropbox. This will then prompt them to login
and start syncing.
--------------------------------------
- Run test suite?
- Add new tests?
- Consider security implications and practices?

Automatically open Dropbox

---

script/setup_secrets

The previous implimentation stored the path of the image in
`Dropbox/.dropbox_secrets_path_$(hostname -s)` which annoyingly wasn't
visible in the dropbox.com UI. We move it to a more visible location.
We also collect everything under `Documents/secrets/$(hostname -s)` to
keep things organized instead of having many files in the dropbox root.
I was curious about moving more stuff into the secrets volume so I
chatted with GPT about the sparse disk options and it mentioned
sparsebundles having better network reslience. I'll give it a shot and
see.
I also moved the secrets volume to iCloud `Documents` because so it
should automatically sync to a new laptop when I log in with my iCloud
account. …

Improve setup_secrets

---

script/install/system_preferences

Many of these locations changed, so I updated the script to reflect the
new locations as I went through. I also automated a few more settings
while at it.
--------------------------------------
- Run test suite?
- Add new tests?
- Consider security implications and practices?

Update system prefs setup for new macOS versions
